### ISSUE TITLE
Python dependency (requirements.txt)

### ISSUE THREAD

**Issue by 4b11b4** [4b11b4/potify#6]
Should the python version we are using be in the req.txt?

Did I setup the venv incorrect?

**Comment by zachcalvert** [comment]
The python version is required to setup the virtualenv, so python needs to be configured before anything in requirements.txt gets installed.

Are you seeing issues with your virtualenv?

**Comment by 4b11b4** [comment]
When we created the virtualenv, we specified which version of python to use.
